### ISSUE TITLE
IA review after analytics and heatmap reports

### ISSUE THREAD

**Issue by leobalter** [gruntjs/gruntjs.com#143]
After a Google Analytics and heatmap analytics, there came out some ideas to enhance the user experience on the website. The following issues were created to allow sharing an open discussion with the community.

This issue can be considered a meta-issue to keep track of them as a group.

- [ ] #133 Add a `Configuring tasks` link on the header nav.
- [x] #134 Gruntfile samples
- [x] #135 clarify npm/github links on the sidebar
- [ ] #136 "How to download" link on the sidebar, after the listed versions
- [ ] #137 Github link on the API page's sidebar
- [ ] #138 Auto select and/or copy shell command examples on click
- [x] #139 Add an example on installing a grunt plugin through npm
- [x] #140 Add a "plugins" link to the "Installing Grunt and gruntplugins" section
- [ ] #141 Add install and create plugins links on the Plugins page
- [ ] #142 Gruntfile builder mini-app

General discussion can be placed here.

cc @cowboy
