### ISSUE TITLE
Content Roadmap For Tutorials/Screencasts

### ISSUE THREAD

**Issue by khalillechelt** [gruntjs/gruntjs.com#69]
Document all the things!
- [ ] Getting started: How to install node.js, npm & and Grunt.js
- [ ] Getting started: How to create a package.json using npm init
- [ ] Getting started: How to create a Gruntfile using grunt-init or generator-gruntfile
- [ ] How to install plugins
- [ ] How and why to use --save-dev
- [ ] What are the grunt-contrib-\* plugins?
- [ ] for each grunt-contrib-*: How to use it and why (this is quite an extensive point)
- [ ] How to search for plugins
- [ ] Best practices
- [ ] what is time-grunt? How to use?
- [ ] What is load-grunt-tasks? How to use?
- [ ] How to deploy to gh-pages with grunt
- [ ] How to deploy via ssh with grunt
- [ ] How to deploy via sftp with grunt
- [ ] How to use Jenkins(?)
- [ ] How to write a simple plugin using grunt-init or generator-gruntplugin
- [ ] How to write a more complex plugin (how to properly organize the code, add tests etc.)
- [ ] How to file an issue for weak documentation or a bug on Github
- [ ] How to participate in the community
- [ ] How to split a large Gruntfile into much smaller, per-task files

Suggestions welcome!
